af: {
   discordBots: 'Discord Bots',
   bestBots: 'Vind die beste Discord Bots vir jou bediener met Botlist.me',
   searchBot: 'Soek vir \'n bot...',
   searchBots: 'Soek vir Discord Bots',
   selectTag: 'Kies \'n merker',
   music: 'Musiek',
   moderation: 'Moderering',
   economy: 'Ekonomie',
   game: 'Speletjie',
   leveling: 'Nivellering',
   fun: 'Pret',
   topBots: 'Topgestemde bots',
   topBotsDesc: 'Topgestemde bots van hierdie maand.',
   certified: 'Gesertifiseer',
   viewBot: 'Bekyk Bot',
   vote: 'Stem',
   tags: 'Merkers',
   tag: 'Merker',
   none: 'Geen',
   anime: 'Anime',
   meme: 'Meme',
   social: 'Sosiaal',
   roleplay: 'Rolspel',
   rolemanagement: 'Rolbestuur',
   logging: 'Tekening',
   dashboard: 'Web Dashboard',
   stream: 'Stroom',
   crypto: 'Kripto',
   media: 'Media',
   turkish: 'Turks',
   soundboard: 'Klankbord',
   utility: 'Nut',
   customizable: 'Aanpasbare gedrag',
   randomBots: 'Ewekansige bots',
   randomBotsDesc: 'Hierdie bots word elke uur gerandomiseer.',
   certBots: 'Gesertifiseerde bots',
   certBotsDesc: 'Hierdie bots is gesertifiseer deur Botlist.me administrateurs.',
   explore: 'Verken meer bots',
   exploreDesc: 'Klik op \'n merker om bots te sien wat die merker het.',
   bots: 'Bots',
   viewMore: 'Vind meer Discord Bots',
   navBots: 'Bots',
   navAdd: 'Voeg bot by',
   navCertification: 'Sertifisering',
   navSupport: 'Ondersteuning',
   navDocs: 'Dokumente',
   navLogin: 'Teken in met Discord',
   navLogout: 'Teken uit',
   navProfile: 'Profiel',
   navSettings: 'Instellings',
   navStaff: 'Personeelpaneel',
   navAdmin: 'Admin Paneel',
   advSettings: 'Gevorderde instellings',
   noFound: 'Geen bot is gevind deur jou soeknavraag',
   add: 'Voeg {bot} by',
   upvote: 'Stem op {bot}',
   review: 'Resensie {bot}',
   rated: 'Gegradeer <b>{stars}</b> uit <b>{count}</b> resensies',
   upvotes: '<b>{count}</b> opstemme hierdie maand',
   information: 'Inligting',
   shortDesc: 'Kort beskrywing',
   prefix: 'Voorvoegsel',
   servers: 'Bedieners',
   shards: 'Skerwe',
   library: 'Biblioteek',
   links: 'Skakels',
   website: 'Webwerf van {bot}',
   support: 'Ondersteuning Bediener van {bot}',
   developer: 'Ontwikkelaar van {bot}',
   ownerControls: 'Eienaarkontroles',
   editBot: 'Wysig Bot',
   staffControls: 'Personeelkontroles',
   deleteBot: 'Skrap Bot',
   adminControls: 'Admin kontroles',
   reviews: 'Resensies',
   noReviews: 'Hierdie bot het geen resensies nie. Klik <a href="{here}">hier</a> om \'n resensie te skryf.',
   noReview: 'Geen resensie is verskaf nie.',
   reviewText: 'Resensie',
   notListed: 'Dit lyk of hierdie bot nie op Botlist.me gelys is nie',
   notListedDesc: 'Dit is dalk verwyder of het dit dalk nooit bestaan nie?',
   goHome: 'Gaan na Tuisblad',
   notLoggedIn: 'Jy is nie aangemeld nie',
   notLoggedInDesc: 'Jy moet aangemeld wees voordat jy vir hierdie bot kan stem. Deur op die aanmeldknoppie te klik, sal jy na Discord herlei word om jou aanmelding te voltooi en dan terug na hierdie bladsy herlei word om vir hierdie bot te stem.',
   voteText: 'Klik op die stemknoppie hieronder om vir hierdie bot te stem',
   voteSuccess: 'Dankie! Jou stem is geregistreer. Jy kan oor 12 ure weer vir hierdie bot stem',
   back: 'Terug',
   vote: 'Stem',
   voteLogin: 'Jy moet aanmeld voordat jy kan stem',
   rating: 'Gradering',
   reviewComment: 'Hersien opmerking',
   sendReview: 'Stuur resensie',
   reviewSuccess: 'Dankie! Jou resensie is geregistreer',
   reviewLogin: 'Jy moet aanmeld voordat jy kan hersien',
   reviewStars: 'Jy moet eers \'n aantal sterre spesifiseer',
 }
