de: {
          discordBots: 'Discord Bots',
          bestBots: 'Finde die besten Discord Bots für deinen Server mit Botlist.me!',
          searchBot: 'Suche nach einem Bot...',
          searchBots: 'Suche nach Discord Bots...',
          selectTag: 'Wähle einen Tag!',
          music: 'Musik',
          moderation: 'Moderation',
          economy: 'Wirtschaft',
          game: 'Game',
          leveling: 'Leveling',
          fun: 'Spaß',
          topBots: 'Top-bewertete Bots.',
          topBotsDesc: 'Top-bewertete Bot in diesen Monat.',
          certified: 'Zertifiziert',
          viewBot: 'Bot Ansehen',
          vote: 'Vote',
          tags: 'Tags',
          tag: 'Tag',
          none: 'None',
          anime: 'Anime',
          meme: 'Meme',
          social: 'Soziales',
          roleplay: 'Rollenspiel',
          rolemanagement: 'Rollenmanagement',
          logging: 'Protokollierung',
          dashboard: 'Web Dashboard',
          stream: 'Stream',
          crypto: 'Krypto',
          media: 'Media',
          turkish: 'Türkisch',
          soundboard: 'Soundboard',
          utility: 'Nützliches',
          customizable: 'Anpassbares Verhalten',
          randomBots: 'Zufällige Bots',
          randomBotsDesc: 'Diese Bots werden stündlich zufällig ausgewählt.',
          certBots: 'Zertifizierte Bots',
          certBotsDesc: 'Diese Bots wurden von den Administratoren von Botlist.me zertifiziert.',
          explore: 'Entdecke mehr Bots!',
          exploreDesc: 'Klicke auf einen Tag um Bots mit diesen Tag anzuzeigen.',
          bots: 'Bots',
          viewMore: 'Sehe dir mehr Bots an!',
          navBots: 'Bots',
          navAdd: 'Bot hinzufügen',
          navCertification: 'Zertifizierung',
          navSupport: 'Hilfe',
          navDocs: 'Doks',
          navLogin: 'mit Discord anmelden',
          navLogout: 'Abmelden',
          navProfile: 'Profil',
          navSettings: 'Einstellungen',
          navStaff: 'Mitarbeiter Panel',
          navAdmin: 'Administrations Panel',
          advSettings: 'Erweiterte Einstellungen',
          noFound: 'Es wurde kein Bot gefunden, der Ihrer Suchanfrage entspricht.',
          add: 'Hinzufügen {bot}',
          upvote: 'Upvote {bot}',
          review: 'Bewerten {bot}',
          rated: 'Bewertet <b>{stars}</b> von <b>{count}</b> Sternen.',
          upvotes: '<b>{count}</b> upvotes this months',
          information: 'Information',
          shortDesc: 'Kurze Beschreibung',
          prefix: 'Prefix',
          servers: 'Servers',
          shards: 'Shards',
          library: 'Library',
          links: 'Links',
          website: 'Webseite von {bot}',
          support: 'Support Server von {bot}',
          developer: 'Entwickler von {bot}',
          ownerControls: 'Besitzer Einstellungen',
          editBot: 'Bot bearbeiten',
          staffControls: 'Mitarbeiter Einstellungen',
          deleteBot: 'Bot löschen',
          adminControls: 'Administrations Einstellungen',
          reviews: 'Bewertungen',
          noReviews: 'Dieser Bot hat keine Bewertungen. Klicke <a href="{here}">hier</a> um eine Bewertung zu schreiben.',
          noReview: 'Es wurde keine Bewertung angegeben.',
          reviewText: 'Bewertung',
          notListed: 'Sieht aus als wäre dieser Bot nicht auf Botlist.me gelistet.',
          notListedDesc: 'Die Beschreibung wurde eventuell entfernt oder hat nie existiert.',
          goHome: 'Zurück zur Hauptseite',
          notLoggedIn: 'Du bist nicht angemeldet!',
          notLoggedInDesc: 'Du musst dich zuerst anmelden.',
          voteText: 'Klicke unten auf den Abstimmungs-Knopf um für diesen Bot zu Voten!',
          voteSuccess: 'Dankeschön! Dein Vote wurde erfolgreich eingereicht. Du kannst in 12 Stunden erneut für diesen Bot voten!',
          back: 'Zurück',
          vote: 'Vote',
          voteLogin: 'Du musst dich zuerst anmelden.',
          rating: 'Bewertung',
          reviewComment: 'Bewertung',
          sendReview: 'Bewertung senden',
          reviewSuccess: 'Erfolgreich! Danke, deine Bewertung ist nun öffentlich.',
          reviewLogin: 'Du musst dich zuerst anmelden.',
          reviewStars: 'Gebe zuerst eine Anzahl an Sternen an!',
        }
