nl: {
          discordBots: 'Discord Bots',
          bestBots: 'Vind de beste Discord Bots voor jouw server met Botlist.me',
          searchBot: 'Zoek voor een bot...',
          searchBots: 'Zoek voor Discord Bots',
          selectTag: 'Selecteer een tag',
          music: 'Muziek',
          moderation: 'Moderatie',
          economy: 'Economie',
          game: 'Game',
          leveling: 'Levels',
          fun: 'Plezier',
          topBots: 'Meest gestemde bots',
          topBotsDesc: 'Meest gestemde bots van deze maand.',
          certified: 'Gecertificeerd',
          viewBot: 'Kijk naar bot',
          vote: 'Stem',
          tags: 'Tags',
          tag: 'Tag',
          none: 'Niet Beschikbaar',
          anime: 'Anime',
          meme: 'Meme',
          social: 'Sociaal',
          roleplay: 'Roleplay',
          rolemanagement: 'Rollen Beheer',
          logging: 'Loggen',
          dashboard: 'Web Dashboard',
          stream: 'Stream',
          crypto: 'Crypto',
          media: 'Media',
          turkish: 'Turks',
          soundboard: 'Soundboard',
          utility: 'Nutsvoorziening',
          customizable: 'Aanpasbaar Gedrag',
          randomBots: 'Willekeurige Bots',
          randomBotsDesc: 'Deze bots worden willekeurig gekozen elk uur.',
          certBots: 'Gecertificeerde Bots',
          certBotsDesc: 'Deze bots zijn gecertificeerd door Botlist.me beheerders.',
          explore: 'Zoek naar meer bots',
          exploreDesc: 'Klik op een tag om meer bots te zien die deze tag hebben.',
          bots: 'Bots',
          viewMore: 'Kijk naar meer Discord bots',
          navBots: 'Bots',
          navAdd: 'Voeg Bot Toe',
          navCertification: 'Certificering',
          navSupport: 'Hulp',
          navDocs: 'Documenten',
          navLogin: 'Log in met Discord',
          navLogout: 'Log uit',
          navProfile: 'Profiel',
          navSettings: 'Instellingen',
          navStaff: 'Personeels Paneel',
          navAdmin: 'Beheerders Paneel',
          advSettings: 'Geadvanceerde Instellingen',
          noFound: 'We konden geen bot vinden die naar jou zoek opdrachten vol doet',
          add: 'Voeg {bot} toe',
          upvote: 'Stem op {bot}',
          review: 'Beoordeel {bot}',
          rated: 'Waardering <b>{stars}</b> van de <b>{count}</b> beoordelingen',
          upvotes: '<b>{count}</b> stemmen deze maand',
          information: 'Informatie',
          shortDesc: 'Korte Beschrijving',
          prefix: 'Prefix',
          servers: 'Servers',
          shards: 'Shards',
          library: 'Biblioteek',
          links: 'Links',
          website: 'Website van {bot}',
          support: 'Hulp Server van {bot}',
          developer: 'Developer van {bot}',
          ownerControls: 'Eigenaar Controles',
          editBot: 'Pas Bot Aan',
          staffControls: 'Personeel Controles',
          deleteBot: 'Verwijder Bot',
          adminControls: 'Beheerder Controles',
          reviews: 'Beoordelingen',
          noReviews: 'Deze bot heeft nog geen beoordelingen. Klik <a href="{here}">hier</a> om een beoordeling te schrijven.',
          noReview: 'Geen beoordeling was ingevuld.',
          reviewText: 'Beoordeel',
          notListed: 'Het ziet er naar uit dat deze bot niet op Botlist.me staat',
          notListedDesc: 'Misschien is hij verwijdert of hij bestond nooit?',
          goHome: 'Ga naar de home pagina',
          notLoggedIn: 'Je bent niet ingelogd',
          notLoggedInDesc: 'Je moet ingelogd zijn om een stem uit te brengen op deze bot. Door te klikken op de log in knop kun je via Discord in loggen, je zult daarna terug gebracht worden naar deze pagina zodat je kunt stemmen op deze bot.',
          voteText: 'Klik op de stem knop hier beneden om op deze bot te stemmen',
          voteSuccess: 'Bedankt! Je stem is geregiseerd. Je kan na 12 uur opnieuw stemmen',
          back: 'Terug',
          vote: 'Stem',
          voteLogin: 'Je moet in loggen om te kunnen stemmen',
          rating: 'Beoordeling',
          reviewComment: 'Beoordeling Toevoeging',
          sendReview: 'Verstuur Beoordeling',
          reviewSuccess: 'Bedankt! Je beoordeling is geregiseerd',
          reviewLogin: 'Je moet in loggen voor dat je kan beoordelen',
          reviewStars: 'Je moet een aantal sterren selecteren om door te gaan',
        }
