en: {
          discordBots: 'Discord Bots',
          bestBots: 'Find the best Discord Bots for your server with Botlist.me',
          searchBot: 'Search for a bot...',
          searchBots: 'Search For Discord Bots',
          selectTag: 'Select a tag',
          music: 'Music',
          moderation: 'Moderation',
          economy: 'Economy',
          game: 'Game',
          leveling: 'Leveling',
          fun: 'Fun',
          topBots: 'Top Voted Bots',
          topBotsDesc: 'Top voted bots of this month.',
          certified: 'Certified',
          viewBot: 'View Bot',
          vote: 'Vote',
          tags: 'Tags',
          tag: 'Tag',
          none: 'None',
          anime: 'Anime',
          meme: 'Meme',
          social: 'Social',
          roleplay: 'Roleplay',
          rolemanagement: 'Role Management',
          logging: 'Logging',
          dashboard: 'Web Dashboard',
          stream: 'Stream',
          crypto: 'Crypto',
          media: 'Media',
          turkish: 'Turkish',
          soundboard: 'Soundboard',
          utility: 'Utility',
          customizable: 'Customizable Behavior',
          randomBots: 'Random Bots',
          randomBotsDesc: 'These bots are randomized every hour.',
          certBots: 'Certified Bots',
          certBotsDesc: 'These bots have been certified by Botlist.me administrators.',
          explore: 'Explore more bots',
          exploreDesc: 'Click on a tag to see bots that have the tag.',
          bots: 'Bots',
          viewMore: 'View more Discord Bots',
          navBots: 'Bots',
          navAdd: 'Add Bot',
          navCertification: 'Certification',
          navSupport: 'Support',
          navDocs: 'Docs',
          navLogin: 'Login with Discord',
          navLogout: 'Logout',
          navProfile: 'Profile',
          navSettings: 'Settings',
          navStaff: 'Staff Panel',
          navAdmin: 'Admin Panel',
          advSettings: 'Advanced Settings',
          noFound: 'No bot was found that met your search query',
          add: 'Add {bot}',
          upvote: 'Upvote {bot}',
          review: 'Review {bot}',
          rated: 'Rated <b>{stars}</b> out of <b>{count}</b> reviews',
          upvotes: '<b>{count}</b> upvotes this months',
          information: 'Information',
          shortDesc: 'Short Description',
          prefix: 'Prefix',
          servers: 'Servers',
          shards: 'Shards',
          library: 'Library',
          links: 'Links',
          website: 'Website of {bot}',
          support: 'Support Server of {bot}',
          developer: 'Developer of {bot}',
          ownerControls: 'Owner Controls',
          editBot: 'Edit Bot',
          staffControls: 'Staff Controls',
          deleteBot: 'Delete Bot',
          adminControls: 'Admin Controls',
          reviews: 'Reviews',
          noReviews: 'This bot has no reviews yet. Click <a href="{here}">here</a> to write a review.',
          noReview: 'No review was provided.',
          reviewText: 'Review',
          notListed: 'Looks like this bot isn\'t listed on Botlist.me',
          notListedDesc: 'It might have been removed or perhaps it never existed?',
          goHome: 'Go to Homepage',
          notLoggedIn: 'You are not logged in',
          notLoggedInDesc: 'You need to be logged in before you can vote for this bot. By clicking the login button, you will be redirected to Discord to complete your login and then redirected back to this page to vote for this bot.',
          voteText: 'Click the vote button below to vote for this bot',
          voteSuccess: 'Thank you! Your vote has been registered. You can vote for this bot again in 12 hours',
          back: 'Back',
          vote: 'Vote',
          voteLogin: 'You need to login before you can vote',
          rating: 'Rating',
          reviewComment: 'Review Comment',
          sendReview: 'Send Review',
          reviewSuccess: 'Thank you! Your review has been registered',
          reviewLogin: 'You need to login before you can review',
          reviewStars: 'You need to specify an amount of stars first',
        }
