tr: {
          discordBots: 'Discord Botları',
          bestBots: 'Botlist.me ile sunucunuza için en iyi Discord Botlarını bulun',
          searchBot: 'Bir bot arayın...',
          searchBots: 'Discord Botları Aratın',
          selectTag: 'Bir etiket seçin',
          music: 'Müzik',
          moderation: 'Moderasyon',
          economy: 'Ekonomi',
          game: 'Oyun',
          leveling: 'Seviye Sistemi',
          fun: 'Eğlence',
          topBots: 'En çok oy alan botlar',
          topBotsDesc: 'Bu ayın en çok oy alan botları.',
          certified: 'Sertifikalı',
          viewBot: 'Botu Görüntüle',
          vote: 'Oy Ver',
          tags: 'Etiketler',
          tag: 'Etiket',
          none: 'Yok',
          anime: 'Anime',
          meme: 'Meme',
          social: 'Sosyal',
          roleplay: 'Rol Yapma',
          rolemanagement: 'Rol Yönetimi',
          logging: 'Kayıt Tutma',
          dashboard: 'Web Paneli',
          stream: 'Yayın',
          crypto: 'Kripto',
          media: 'Medya',
          turkish: 'Türkçe',
          soundboard: 'Ses Panosu',
          utility: 'Yardımcı Fonksiyonlar',
          customizable: 'Özelleştirilebilir Davranış',
          csgo: 'CS:GO',
          rl: 'Rocket League',
          pubg: 'PUBG',
          fortnite: 'Fortnite',
          overwatch: 'Overwatch',
          amongus: 'Among Us',
          osu: 'OSU!',
          minecraft: 'Minecraft',
          lol: 'League of Legends',
          warframe: 'Warframe',
          diablo: 'Diablo III',
          randomBots: 'Rastgele Botlar',
          randomBotsDesc: 'Bu botlar her saat rastgele değişir.',
          certBots: 'Sertifikalı Botlar',
          certBotsDesc: 'Bu botlar Botlist.me yöneticileri tarafından sertifikalandırılmıştır.',
          explore: 'Daha fazla bot keşfet',
          exploreDesc: 'Bir etikete tıklayarak o etikete sahip botları görebilirsiniz.',
          bots: 'Botları',
          viewMore: 'Daha fazla Discord Botu görüntüle',
          navBots: 'Botlar',
          navAdd: 'Bot Ekle',
          navCertification: 'Sertifikalama',
          navSupport: 'Destek',
          navDocs: 'Dokümantasyon',
          navLogin: 'Discord ile giriş yap',
          navLogout: 'Çıkış yap',
          navProfile: 'Profil',
          navSettings: 'Ayarlar',
          navStaff: 'Personel Paneli',
          navAdmin: 'Yönetici Paneli',
          advSettings: 'Gelişmiş Ayarlar',
          noFound: 'Arama kriterlerinize uygun bot bulunamadı',
          add: '{bot} Ekle',
          upvote: '{bot} Oy Ver',
          review: '{bot} İnceleme Yaz',
          rated: '<b>{count}</b> inceleme üzerinden <b>{stars}</b> puan aldı',
          upvotes: 'Bu ay <b>{count}</b> oy aldı',
          information: 'Bilgiler',
          shortDesc: 'Kısa Açıklama',
          prefix: 'Ön Ek',
          servers: 'Sunucu Sayısı',
          shards: 'Shardlar',
          library: 'Kütüphane',
          links: 'Linkler',
          website: '{bot} Websitesi',
          support: '{bot} Destek Sunucusu',
          developer: '{bot} Geliştiricisi',
          ownerControls: 'Geliştirici Kontrolleri',
          editBot: 'Botu Düzenle',
          staffControls: 'Personel Kontrolleri',
          deleteBot: 'Botu Sil',
          adminControls: 'Yönetici Kontrolleri',
          reviews: 'İncelemeler',
          noReviews: 'Bu bot hakkında henüz bir yorum yok. Yorum yazmak için <a href="{here}">buraya</a> tıklayın.',
          noReview: 'Bir yorum girilmedi.',
          reviewText: 'Yorum',
          notListed: 'Görünüşe göre bu bot Botlist.me\'de listelenmiyor',
          notListedDesc: 'Bu bot kaldırılmış olabilir ya da belki de hiç var olmamıştır?',
          goHome: 'Ana sayfaya dön',
          notLoggedIn: 'Giriş yapmadınız',
          notLoggedInDesc: 'Bu botu oylayabilmeniz için önce giriş yapmanız gerekmektedir. Giriş düğmesine tıkladığınızda girişinizi tamamlamak için Discord\'a yönlendirileceksiniz ve ardından bu bota oy vermek için bu sayfaya geri yönlendirileceksiniz.',
          voteText: 'Bu bota oy vermek için aşağıdaki oy ver düğmesine tıklayın',
          voteSuccess: 'Teşekkür ederiz! Oyunuz kaydedildi. Bu bot için 12 saat içinde tekrar oy verebilirsiniz',
          back: 'Geri',
          vote: 'Oy Ver',
          voteLogin: 'Oy kullanabilmeniz için önce giriş yapmanız gerekiyor',
          rating: 'Puan',
          reviewComment: 'Yorumunuz',
          sendReview: 'İncelemeyi Gönder',
          reviewSuccess: 'Teşekkürler! Yorumunuz kaydedildi',
          reviewLogin: 'Yorum yazabilmeniz için önce giriş yapmanız gerekiyor',
          reviewStars: 'Önce bir yıldız miktarı belirlemeniz gerekli',
        }
